### ISSUE TITLE
イデアルを使用しない

### ISSUE THREAD

**Issue by ghost** [Seasawher/number-theory-with-lean#1]
イデアルなしで証明することもできるので，便利な言葉としてだけ導入するのではなく，最初からイデアルの使用を回避した方が良いのではないかと思いました．

たとえば a = b q + r であるとき，a と b の公約数全体と b と r の公約数全体は一致することが示せるはずです．

**Comment by Seasawher** [comment]
なるほど，確かにそうですね！

ありがとうございました．
